SELECT * FROM TESTE 
SELECT LEFT(ANO_T,4) ANO ,RIGHT(ANO_T,2) TRIMESTRE,*  FROM TESTE WHERE ANO_T LIKE'%T1' 
SELECT LEFT(ANO_T,4) ANO ,RIGHT(ANO_T,2) TRIMESTRE,*  FROM TESTE WHERE ANO_T LIKE'2008%' 
